language: csharp
mono: none
dotnet: 2.1.0

env:
  - PATH="${PATH}:~/.dotnet/tools"
  
git:
  depth: false

addons:
  sonarcloud:
    organization: "reality77-github"

install:
  - dotnet tool install --global dotnet-sonarscanner --version 4.6.1
  
script:
 - dotnet sonarscanner begin
 - dotnet restore
 - dotnet build
 - dotnet sonarscanner end
