services:
  webapp:
    image: web
    environment:
      APP_DB_SERVER: localhost  # or the IP address of your VPS
      APP_DB_USER: rcbenevoles
      APP_DB_PASSWORD: jw8s0F5
      APP_DB_PORT: 5432
      APP_GENERATE_DEV_DATA: 0
      APP_LOG_FILE_PATH: /var/log/rcb.log
      APP_DB_BACKUP_PATH: /var/backups
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      - log_data:/var/log
      - db_backups:/var/backups:ro
      - external_data:/app/external:ro
    networks:
      - backnet

networks:
  backnet:
    driver: bridge

volumes:
  log_data:
  db_backups:
  external_data:
  db_data: