version: '3.5'

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: rcbenevoles
      POSTGRES_PASSWORD: rcbenevoles
      POSTGRES_DB : rcbenevoles
    hostname: db
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
