export APP_DB_SERVER=localhost
export APP_DB_PASSWORD=rcbenevoles
export APP_GENERATE_DEV_DATA=1
export APP_ADMIN_PASSWORD=admin
export APP_LOG_FILE_PATH=logs/rcb.log
export APP_DB_BACKUP_PATH=db_backups